//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeatSaber_FakeMultiplay.Client.ResourceFiles.Shared {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SharedResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharedResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BeatSaber_FakeMultiplay.Client.ResourceFiles.Shared.SharedResource", typeof(SharedResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Who&apos;s Sakura?.
        /// </summary>
        public static string AboutMeLinkText {
            get {
                return ResourceManager.GetString("AboutMeLinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sakura Beat Saber.
        /// </summary>
        public static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alpha Testers.
        /// </summary>
        public static string CreditAlphaTesterText {
            get {
                return ResourceManager.GetString("CreditAlphaTesterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string CreditSiteBuilderTitle {
            get {
                return ResourceManager.GetString("CreditSiteBuilderTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credits.
        /// </summary>
        public static string NavCreditText {
            get {
                return ResourceManager.GetString("NavCreditText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        public static string NavHomeText {
            get {
                return ResourceManager.GetString("NavHomeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiplay.
        /// </summary>
        public static string NavLobbyText {
            get {
                return ResourceManager.GetString("NavLobbyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here is a special thanks for all the people helped with building the site..
        /// </summary>
        public static string SpecialThanksDescriptionText {
            get {
                return ResourceManager.GetString("SpecialThanksDescriptionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join my Discord~.
        /// </summary>
        public static string SupportLinkText {
            get {
                return ResourceManager.GetString("SupportLinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A new version of the application is available. Click here to update..
        /// </summary>
        public static string UpdateAvailablePopupText {
            get {
                return ResourceManager.GetString("UpdateAvailablePopupText", resourceCulture);
            }
        }
    }
}
