//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeatSaber_FakeMultiplay.Client.ResourceFiles.Lobby {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LobbyResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LobbyResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BeatSaber_FakeMultiplay.Client.ResourceFiles.Lobby.LobbyResource", typeof(LobbyResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beat Saber is not running..
        /// </summary>
        public static string BeatSaberNotRunningMessage {
            get {
                return ResourceManager.GetString("BeatSaberNotRunningMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string CopyOverlayLinkButtonText {
            get {
                return ResourceManager.GetString("CopyOverlayLinkButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create / Join.
        /// </summary>
        public static string CreateRoomButtonText {
            get {
                return ResourceManager.GetString("CreateRoomButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiplay requires {0} or {1} to work. &lt;br/&gt;&lt;br/&gt; * Apparently accuracy works with HttpSiraStatus only..
        /// </summary>
        public static string HttpStatusConnectionFailText {
            get {
                return ResourceManager.GetString("HttpStatusConnectionFailText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect.
        /// </summary>
        public static string JoinButtonText {
            get {
                return ResourceManager.GetString("JoinButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is how your name will appear on the scoreboard..
        /// </summary>
        public static string PlayerNameHintText {
            get {
                return ResourceManager.GetString("PlayerNameHintText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player Name.
        /// </summary>
        public static string PlayerNameLabelText {
            get {
                return ResourceManager.GetString("PlayerNameLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anyone has the name can join your room..
        /// </summary>
        public static string RoomNameHintText {
            get {
                return ResourceManager.GetString("RoomNameHintText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Room name.
        /// </summary>
        public static string RoomNameLabelText {
            get {
                return ResourceManager.GetString("RoomNameLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share Room.
        /// </summary>
        public static string ShareRoomButtonText {
            get {
                return ResourceManager.GetString("ShareRoomButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  has entered the room..
        /// </summary>
        public static string UserEnterRoomMessage {
            get {
                return ResourceManager.GetString("UserEnterRoomMessage", resourceCulture);
            }
        }
    }
}
